[package]
name = "bothan-core"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.57"
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = "0.7.10"
tracing = "0.1.40"
log = "0.4.20"
serde = { version = "1.0.196", features = ["std", "derive", "alloc"] }
derive_more = { version = "1.0.0-beta.6", features = ["full"] }
async-trait = "0.1.77"
