[package]
name = "bothan-core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
rust_decimal = { workspace = true, features = ["maths"] }
itertools = { workspace = true }

bincode = "1.3.3"
num-traits = "0.2.19"
petgraph = "0.6.4"
prost = "0.13.1"
rust-rocksdb = "0.28.0"
tonic = "0.12.1"
chrono = "0.4.38"
serde_json = "1.0.120"

