[workspace.package]
version = "0.1.8"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = ["bothan-api", "bothan-binance", "bothan-bybit", "bothan-coingecko", "bothan-core", "bothan-cryptocompare", "bothan-htx"]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.77"
chrono = "0.4.38"
derive_more = { version = "1.0.0-beta.6", features = ["full"] }
futures = "0.3.30"
humantime-serde = "1.1.1"
itertools = "0.12.1"
mockito = "1.4.0"
reqwest = { version = "0.12.3", features = ["json"] }
serde = { version = "1.0.197", features = ["std", "derive", "alloc"] }
serde_json = "1.0.116"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
tokio-util = "0.7.10"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.0"

bothan-core = { version = "0.1.0", path = "bothan-core" }
bothan-binance = { version = "0.1.0", path = "bothan-binance" }
bothan-bybit = { version = "0.1.0", path = "bothan-bybit" }
bothan-coingecko = { version = "0.1.0", path = "bothan-coingecko" }
bothan-coinmarketcap = { version = "0.1.0", path = "bothan-coinmarketcap" }
bothan-cryptocompare = { version = "0.1.0", path = "bothan-cryptocompare" }
bothan-htx = { version = "0.1.0", path = "bothan-htx" }
