[workspace.package]
version = "0.1.8"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = ["price-adapter-raw", "price-adapter", "bothan-binance", "bothan-core", "bothan-coin-gecko"]
resolver = "2"

[workspace.dependencies]
price-adapter = { version = "0.1.8", path = "price-adapter" }
price-adapter-raw = { version = "0.1.8", path = "price-adapter-raw" }
bothan-core = { version = "0.1.0", path = "bothan-core" }
bothan-binance = { version = "0.1.0", path = "bothan-binance" }
bothan-coin-gecko = { version = "0.1.0", path = "bothan-coin-gecko" }
