[workspace.package]
version = "0.1.8"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = ["bothan-api", "bothan-binance", "bothan-coingecko", "bothan-core", "bothan-cryptocompare", "bothan-htx"]
resolver = "2"

[workspace.dependencies]
url = "2.5.0"
futures = "0.3.30"
async-trait = "0.1.77"
reqwest = { version = "0.11.24", features = ["json"] }
thiserror = "1.0.57"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
serde = { version = "1.0.197", features = ["std", "derive", "alloc"] }
humantime-serde = "1.1.1"
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = "0.7.10"
derive_more = { version = "1.0.0-beta.6", features = ["full"] }

bothan-core = { version = "0.1.0", path = "bothan-core" }
bothan-binance = { version = "0.1.0", path = "bothan-binance" }
bothan-coingecko = { version = "0.1.0", path = "bothan-coingecko" }
bothan-coinmarketcap = { version = "0.1.0", path = "bothan-coinmarketcap" }
bothan-cryptocompare = { version = "0.1.0", path = "bothan-cryptocompare" }
bothan-htx = { version = "0.1.0", path = "bothan-htx" }
