[package]
name = "price-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22", features = ["json"] }
thiserror = "1.0.50"
tracing = "0.1.40"
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = "0.3.17"
serde = { version = "1.0.192", features = ["serde_derive"] }
serde_json = "1.0.108"
itertools = "0.11.0"
