version: '3.8'
services:
  bothan-api:
    build:
      context: .
      dockerfile: bothan-api/server-cli/Dockerfile
    ports:
    - "50051:50051"
  bothan-api-proxy:
    build:
      context: .
      dockerfile: ./bothan-api-proxy/Dockerfile
    ports:
    - "8081:8081"
