version: '3.8'
services:
  bothan-api:
    build:
      context: .
      dockerfile: bothan-api/server/Dockerfile
    volumes:
      - ./bothan-api/config.toml:/app/config.toml
    ports:
      - "50051:50051"
  bothan-api-proxy:
    build:
      context: .
      dockerfile: ./bothan-api-proxy/Dockerfile
    volumes:
      - ./bothan-api-proxy/config.toml:/app/config.toml
    ports:
      - "8081:8081"
