[package]
name = "bothan-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bothan-core = { path = "../bothan-core" }
bothan-binance = { path = "../bothan-binance" }
tracing = { version = "0.1.40", features = [] }
tokio = { version = "1.36.0", features = ["full"] }
tracing-subscriber = "0.3.17"
tonic = "0.11"
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"
