[package]
name = "bothan-api"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bothan-api"
path = "src/main.rs"

[dependencies]
bothan-binance = { workspace = true }
#bothan-bybit = { workspace = true }
#bothan-coinbase = { workspace = true }
bothan-coingecko = { workspace = true }
#bothan-coinmarketcap = { workspace = true }
bothan-core = { workspace = true }
#bothan-cryptocompare = { workspace = true }
#bothan-htx = { workspace = true }
#bothan-kraken = { workspace = true }
#bothan-okx = { workspace = true }

chrono = { workspace = true }
humantime-serde = { workspace = true }
itertools = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

anyhow = "1.0.86"
async-trait = "0.1.81"
config = "0.14.0"
dirs = "5.0.1"
glob = "0.3.1"
prost = "0.13.1"
protoc-gen-prost = "0.3.1"
protoc-gen-tonic = "0.4.0"
tonic = "0.12.1"

[build-dependencies]
tonic-build = "0.12.1"
