[package]
name = "bothan-lib"
version = "0.0.1-alpha.4"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true, features = ["rc"] }
thiserror = { workspace = true }
rust_decimal = { workspace = true, features = ["maths", "serde-str"] }
tokio = { workspace = true }
tracing = { workspace = true }

bincode = "2.0.0-rc.3"
serde_json = "1.0.135"
num-traits = "0.2.19"
