[package]
name = "bothan-api-cli"
version = "0.0.1-beta.1"
rust-version = "1.81"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bothan"
path = "src/main.rs"

[dependencies]
bothan-client = { workspace = true }
bothan-core = { workspace = true }

bothan-api = { workspace = true }
bothan-binance = { workspace = true }
bothan-bybit = { workspace = true }
bothan-coinbase = { workspace = true }
bothan-coingecko = { workspace = true }
bothan-coinmarketcap = { workspace = true }
bothan-cryptocompare = { workspace = true }
bothan-htx = { workspace = true }
bothan-kraken = { workspace = true }
bothan-okx = { workspace = true }

reqwest = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
inquire = "0.7.5"
dirs = "5.0.1"
toml = "0.8.19"
