[package]
name = "bothan-api-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bothan-api = { workspace = true }
bothan-binance = { workspace = true }
bothan-coingecko = { workspace = true }
bothan-core = { workspace = true }

async-trait = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
toml = "0.8.19"
tonic = "0.12.1"

