[package]
name = "bothan-api-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bothan"
path = "src/main.rs"

[dependencies]
bothan-api = { workspace = true }
bothan-binance = { workspace = true }
bothan-coingecko = { workspace = true }
bothan-kraken = { workspace = true }
bothan-core = { workspace = true }

async-trait = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
toml = "0.8.19"
tonic = "0.12.1"
log = "0.4.22"

