[package]
name = "bothan-api-cli"
version = "0.0.1-alpha.4"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bothan"
path = "src/main.rs"

[dependencies]
bothan-core = { workspace = true }
bothan-lib = { workspace = true }
bothan-api = { workspace = true }

bothan-client = { workspace = true }

reqwest = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
dirs = "5.0.1"
log = "0.4.22"
toml = "0.8.19"
