name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.81
        components: rustfmt
        override: true
    - run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.81
        components: clippy
        override: true
    - uses: Swatinem/rust-cache@v2
    - run: cargo clippy --workspace --all-targets --all-features
      env:
        RUSTFLAGS: -D warnings

  test-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.78
        override: true
    - uses: Swatinem/rust-cache@v2
    - run: cargo test --workspace --all-features --no-fail-fast
