name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-02-25
        components: rustfmt
    - run: cargo +nightly-2025-02-25 fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.85
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - run: cargo clippy --workspace --all-targets --all-features
      env:
        RUSTFLAGS: -D warnings

  test-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.85
    - uses: Swatinem/rust-cache@v2
    - run: cargo test --workspace --all-features --no-fail-fast
